kind: pipeline
type: docker
name: compose-v2

steps:
  - name: build-container
    image: plugins/docker
    volumes:
      - name: docker-cache
        path: /var/lib/docker
    settings:
      dockerfile: Dockerfile.compose-v2
      target: output_image
      repo: docker.andne.net/docker/compose-v2
      dry_run: true

  - name: test-container
    image: plugins/docker
    volumes:
      - name: docker-cache
        path: /var/lib/docker
    settings:
      dockerfile: Dockerfile.compose-v2
      target: test_image
      repo: docker.andne.net/docker/compose-v2
      dry_run: true

  - name: publish-container
    image: docker.andne.net/plugins/docker
    volumes:
      - name: docker-cache
        path: /var/lib/docker
    settings:
      dockerfile: Dockerfile.compose-v2
      auto_tag: true
      target: output_image
      repo: docker.andne.net:5000/docker/compose-v2

volumes:
  - name: docker-cache
    temp: {}

---
kind: pipeline
type: docker
name: plugins-docker

steps:
  - name: build-container
    image: plugins/docker
    volumes:
      - name: docker-cache
        path: /var/lib/docker
    settings:
      dockerfile: Dockerfile.plugins-docker
      context: plugins-docker
      target: output_image
      repo: docker.andne.net/plugins/docker
      dry_run: true

  - name: publish-container
    image: docker.andne.net/plugins/docker
    volumes:
      - name: docker-cache
        path: /var/lib/docker
    settings:
      dockerfile: Dockerfile.plugins-docker
      context: plugins-docker
      auto_tag: true
      target: output_image
      repo: docker.andne.net/plugins/docker

volumes:
  - name: docker-cache
    temp: {}
